// Generated by CoffeeScript 1.9.3
Ext.define('HomeTrak.view.AssessmentChoicePanel', {
  extend: 'Ext.tree.Panel',
  xtype: 'assessmentChoicePanel',
  rootVisible: false,
  useArrows: true,
  height: 300,
  initComponent: function() {
    var l10n;
    l10n = HomeTrak.util.Localization;
    this.store = Ext.create('Ext.data.TreeStore', {
      proxy: {
        type: 'ajax',
        url: 'data/assessmentChoices.json'
      }
    });
    this.bbar = [
      '-', {
        xtype: 'button',
        text: l10n.get("client.save")
      }, '-', {
        xtype: 'button',
        text: l10n.get("client.canel_exit")
      }, '-', {
        xtype: 'button',
        text: l10n.get("client.previous")
      }, '-', {
        xtype: 'button',
        text: l10n.get("client.next")
      }, '-', {
        xtype: 'button',
        text: l10n.get("client.save_exit")
      }
    ];
    this.callParent(arguments);
  }
});
