// Generated by CoffeeScript 1.9.3
Ext.define('HomeTrak.view.AssessmentChoicePanel', {
  extend: 'Ext.tree.Panel',
  xtype: 'assessmentChoicePanel',
  rootVisible: false,
  useArrows: true,
  height: 300,
  initComponent: function() {
    this.store = Ext.create('Ext.data.TreeStore', {
      proxy: {
        type: 'ajax',
        url: 'data/assessmentChoices.json'
      }
    });
    this.bbar = [
      '-', {
        xtype: 'button',
        text: 'Save'
      }, '-', {
        xtype: 'button',
        text: 'Cancel/Exit'
      }, '-', {
        xtype: 'button',
        text: 'Previous'
      }, '-', {
        xtype: 'button',
        text: 'Next'
      }, '-', {
        xtype: 'button',
        text: 'Save Exit'
      }
    ];
    this.callParent(arguments);
  }
});
