// Generated by CoffeeScript 1.9.3
var searchObj;

Ext.Loader.setConfig({
  enabled: true
});

Ext.Loader.setPath('Ext.ux', 'ext/ux');

searchObj = Ext.Object.fromQueryString(location.search);

requirejs.config({
  config: {
    i18n: {
      locale: searchObj.locale || 'zh-cn'
    }
  }
});

Ext.application({
  views: ['Home', 'Client', 'Caregiver', 'ClientSearch', 'ClientSchedule', 'AssessmentChoicePanel'],
  controllers: ['Event'],
  requires: ['Ext.tip.QuickTipManager', 'Ext.container.Viewport', 'Ext.layout.*', 'Ext.form.Panel', 'Ext.form.Label', 'Ext.grid.*', 'Ext.data.*', 'Ext.tree.*', 'Ext.selection.*', 'Ext.tab.Panel', 'Ext.ux.form.SearchField', 'Ext.ux.DataTip', 'Ext.ux.layout.Center', 'HomeTrak.util.Localization'],
  name: 'HomeTrak',
  launch: function() {
    require(["nls/i18nModule"], function(i18n) {
      var viewport;
      HomeTrak.util.Localization.init(i18n);
      Ext.tip.QuickTipManager.init();
      viewport = Ext.create('Ext.Viewport', {
        layout: 'card',
        items: [
          {
            xtype: 'caregiver'
          }, {
            xtype: 'home'
          }
        ],
        renderTo: Ext.getBody()
      });
    });
  }
});
