// Generated by CoffeeScript 1.9.3
Ext.define('HomeTrak.controller.Event', {
  extend: 'Ext.app.Controller',
  init: function() {
    this.control({
      'gridpanel[title=Reservations]': {
        itemclick: this.onItemClick,
        viewready: this.onViewReady
      }
    });
  },
  onItemClick: function(grid, record, item, index) {
    var clientId, firstName, lastName, name, phone, summaryInfo;
    summaryInfo = Ext.getCmp('clientSchedule-summaryInfo');
    summaryInfo.setVisible(true);
    clientId = Ext.getCmp("client-id");
    phone = Ext.getCmp("client-phone");
    firstName = Ext.getCmp("client-first-name");
    lastName = Ext.getCmp("client-last-name");
    clientId.setValue(record.get('id'));
    phone.setValue(record.get('phone'));
    name = record.get('name');
    firstName.setValue(name.split(" ")[0]);
    lastName.setValue(name.split(" ")[1]);
  },
  onViewReady: function(grid) {
    var l10n;
    l10n = HomeTrak.util.Localization;
    grid.view.focusRow(0);
    this.onItemClick('', grid.view.getRecord(0));
    Ext.create('Ext.tip.ToolTip', {
      target: grid.view.el,
      delegate: grid.view.itemSelector,
      html: l10n.get('schedule.dbc_for_more_detail')
    });
  }
});
