define({
    "caregiver_name": "护理人"
    "clientSearch": {
        "client_search": "客户查询"
        "client_search_name": "姓名"
    },
    "schedule": {
        "today": "今天"
        "my_clients": "我的客户"
        "reservations": "预约"
        "reservation_name": "姓名"
        "reservation_phone": "电话"
        "reservation_time": "时间"
        "doctor": "医生"
        "doctor_name": "医生姓名"
        "doctor_id": "医生ID"
        "doctor_phone": "医生电话"
    }
    "client": {
        "submit": "提交"
        "analysis": "分析"
        "save": "保存"
        "canel_exit": "取消并退出"
        "previous": "上一个"
        "next": "下一个"
        "save_exit": "保存并退出"
        "profile": "客户简介"
        "basic_info": "基本信息"
        "name": "客户"
        "id": "客户ID"
        "status": "状态"
        "first_name": "姓"
        "last_name": "名"
        "phone": "电话"
        "district": "地区"
        "language": "语言"
        "address": "地址"
        "address2": "地址2"
        "apt": "APT"
        "ssn": "S.S.N"
        "gender": "性别"
        "state": "省"
        "birthday": "生日"
        "city": "市"
        "zip": "邮编"
        "email": "邮箱"

        "general_info": "主要信息"
        "diagnosis_code": "诊断详情"
        "sympton": "症状"
        "sympton2": "症状2"
        "sympton3": "症状3"
        "health_index": "健康指标"
        "heat_beats": "心跳"
        "pressure": "血压"
        "others": "其他"

        "coc_notes": "COC 笔记"

        "goals": "目标"

        "health_maintenance": "健康信息维护"

        "visits": "就诊信息"
        "history": "历史"
        "history_date": "日期"
        "history_time": "时间"
        "history_status": "状态"

        "oasis": "Oasis"
        "soc_assess": "SOC 评测"
        "reqd": "Reqd"
        "no_visit": "没有访问"
        "allergies": "过敏症"
        "vns_allergies": "(VNS0004) 过敏症"
        "drug": "药物"
        "food": "食物"
        "enviornmental": "环境"
        "allergic_reaction": "过敏反应"
        "penicillin": "盘尼西林"
        "sulfa": "复方新诺明"
        "aspirin": "阿司匹林"
        "codeine": "磷酸可待因，磷酸甲基吗啡"
        "other": "其他"
        "anaphylaxis": "过敏反应"
        "diarrhea": "腹泻"
        "nausea_Vomiting": "恶心/呕吐"
        "rash": "（皮）疹"
        "upper_respiratory_symptoms": "上呼吸症状"
        "asthma_attack": "哮喘发作"
        "unknown": "未知"
        "substance_abuse1": "药物滥用1"
        "substance_abuse2": "药物滥用2"
        "substance_abuse3": "药物滥用3"
        "substance_abuse4": "药物滥用4"
    }
});