// Generated by CoffeeScript 1.9.3
Ext.define('HomeTrak.util.Localization', function() {
  var context, localization;
  context = '';
  localization = {
    singleton: true,
    init: function(_context) {
      context = _context;
      this.init = null;
    },
    get: function(path) {
      var i, len, next, p, pathes;
      pathes = path.split(".");
      next = context;
      for (i = 0, len = pathes.length; i < len; i++) {
        p = pathes[i];
        next = next[p];
      }
      return next;
    }
  };
  return localization;
});
