define({
    "root": {
        "caregiver_name": "Caregiver Name"
        "clientSearch": {
            "client_search": "Client Search"
            "client_search_name": "Name"
        },
        "schedule": {
            "today": "Today"
            "my_clients": "My Clients"
            "reservations": "Reservations"
            "reservation_name": "Name"
            "reservation_phone": "Phone"
            "reservation_time": "Time"
            "doctor": "Dr."
            "doctor_name": "Dr. Name"
            "doctor_id": "Dr. ID"
            "doctor_phone": "Phone"
            "dbc_for_more_detail": "double click for more detail"
        }
        "client": {
            "submit": "Submit"
            "analysis": "Analysis"
            "save": "Save"
            "canel_exit": "Cancel/Exit"
            "previous": "Previous"
            "next": "Next"
            "save_exit": "Save Exit"
            "profile": "Profile"
            "basic_info": "Basic Information"
            "name": "Client"
            "id": "Client ID"
            "status": "Status"
            "first_name": "First Name"
            "last_name": "Last Name"
            "phone": "Phone"
            "district": "District"
            "language": "Language"
            "address": "Address"
            "address2": "Address2"
            "apt": "APT"
            "ssn": "S.S.N"
            "gender": "Gender"
            "state": "State"
            "birthday": "Birthday"
            "city": "City"
            "zip": "Zip"
            "email": "Email"

            "general_info": "General Information"
            "diagnosis_code": "Diagnosis Codes"
            "sympton": "Sympton"
            "sympton2": "Sympton2"
            "sympton3": "Sympton3"
            "health_index": "Health Index"
            "heat_beats": "Heart Beats"
            "pressure": "Pressure"
            "others": "Others"

            "coc_notes": "COC Notes"

            "goals": "Goals"

            "health_maintenance": "HEALTH MAINTENANCE"

            "visits": "Visits"
            "history": "History"
            "history_date": "Date"
            "history_time": "Time"
            "history_status": "Status"

            "oasis": "Oasis"
            "soc_assess": "SOC Assessment"
            "reqd": "Reqd"
            "no_visit": "No Visit"
            "allergies": "Allergies"
            "vns_allergies": "(VNS0004) Allergies"
            "drug": "Drug"
            "food": "Food"
            "enviornmental": "Enviornmental"
            "allergic_reaction": "Allergic Reactions"
            "penicillin": "Penicillin"
            "sulfa": "Sulfa"
            "aspirin": "Aspirin"
            "codeine": "Codeine"
            "other": "Other"
            "anaphylaxis": "Anaphylaxis"
            "diarrhea": "Diarrhea"
            "nausea_Vomiting": "Nausea/Vomiting"
            "rash": "Rash"
            "upper_respiratory_symptoms": "Upper respiratory symptoms"
            "asthma_attack": "Asthma attack"
            "unknown": "Unknown"
            "substance_abuse1": "Substance Abuse 1"
            "substance_abuse2": "Substance Abuse 2"
            "substance_abuse3": "Substance Abuse 3"
            "substance_abuse4": "Substance Abuse 4"
        }
    },
    "zh-cn": true
});